# Generated by Django 5.1.1 on 2024-09-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('letter', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('due', models.DateField()),
                ('prio', models.CharField(help_text='low, medium, urgent', max_length=100)),
                ('category', models.IntegerField(help_text='1 = User Story, 2 = Technical Task')),
                ('timestamp', models.BigIntegerField()),
                ('status', models.CharField(default='toDo', help_text='toDo, inProgress, awaitingFeedback, done', max_length=100)),
                ('subtasks', models.JSONField(blank=True, default=list, help_text='status: toDo, inProgress, awaitingFeedback, done', null=True)),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to='join_app.users')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
                'ordering': ['title'],
            },
        ),
    ]
