# Generated by Django 5.1.1 on 2024-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=models.CharField(max_length=100),
        ),
    ]
