# Generated by Django 5.1.1 on 2024-09-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_alter_contacts_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='email',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='tel',
            new_name='number',
        ),
    ]
