# Generated by Django 5.1.1 on 2024-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_delete_users_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=2)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
