# Generated by Django 5.1.1 on 2024-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0004_tasks_subtasks_delete_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
