# Generated by Django 5.1.1 on 2024-09-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_alter_tasks_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks', to='join_app.users'),
        ),
    ]
