# Generated by Django 5.1.1 on 2024-09-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_alter_tasks_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ['name'], 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['title'], 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['name'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='category',
            field=models.IntegerField(help_text='1 = User Story, 2 = Technical Task'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prio',
            field=models.CharField(help_text='low, medium, urgent', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(default='toDo', help_text='toDo, inProgress, awaitingFeedback, done', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='subtasks',
            field=models.JSONField(blank=True, default=list, help_text='status: toDo, inProgress, awaitingFeedback, done', null=True),
        ),
    ]
