# Generated by Django 5.1.1 on 2024-10-09 15:12

from django.db import migrations
from django.contrib.auth.models import User


def create_guest_user(apps):
    UserProfile = apps.get_model('join_auth_app', 'UserProfile')
    
    if not User.objects.filter(username='guest').exists():
        account = User.objects.create_user(
            username='guest',
            email='guest@guest.de',
            password='guest'
        )
        account.first_name = 'Guest'
        account.last_name = 'User'
        account.save()

        initials = 'GU'
        color = '#DC3DF5'
        UserProfile.objects.create(user=account, initials=initials, color=color)


class Migration(migrations.Migration):

    dependencies = [
        ('join_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_guest_user)
    ]
